# Site settings 站点变量
name: YINUPS
motto: "Life is measured by thought and action not by time"
url: "http://yinups.com"
description: "这是尹上升的个人博客。博客包括技术文章和应用。其中文章主要是面向web前端的技术分享，应用是各种js插件和大型web应用。"
tag: "尹上升，博客，web前端，技术分享，js插件，web应用，upyin，upyins,yinup,yinups"

# Build settings
markdown: kramdown          #模版使用kramdown
permalink: /blog/:title 	#url格式

highlighter: pygments       #语法高亮
