# Site settings 站点变量
name: YINUPS
motto: "Life is measured by thought and action not by time"
url: "https://yinups.com"
description: "尹上升博客。专注前端，分享技术。"
tag: "尹上升，博客，前端，技术分享，javascript，upyin，upyins，yinup，yinups"

# Build settings
markdown: kramdown          #模版使用kramdown
permalink: /blog/:title 	#url格式

highlighter: prismjs       #语法高亮
