# Site settings 站点变量
name: YINUPS
motto: "Life is measured by thought and action not by time"
url: "http://yinups.com"
description: "this is yinups's personal blog web."
tag: "yinups blog upyin yinshangsheng"

# Build settings
markdown: kramdown          #模版使用kramdown
permalink: /blog/:title 	#url格式

highlighter: pygments       #语法高亮
