# Site settings 站点变量
name: YINUPS
motto: "Life is measured by thought and action not by time"
url: "http://yinups.com"
description: "尹上升博客。热爱前端，分享技术。"
tag: "尹上升，博客，web前端，技术分享，js插件，web应用，upyin，upyins,yinup,yinups"

# Build settings
markdown: kramdown          #模版使用kramdown
permalink: /blog/:title 	#url格式

highlighter: pygments       #语法高亮
